package com.niko.assistant.localai

import android.content.Context
import com.niko.assistant.ai.LeoStructuredGroq
import com.niko.assistant.devicecontrol.NikoVisualContext
import com.niko.assistant.learning.NikoKnowledgeStore
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * Stable local-first brain facade.
 *
 * Short conversation is generated by MicroGPT. Static open-domain knowledge is retrieved from
 * Leo's separately downloaded ~500 MB frozen brain. Personal/documentary knowledge learned with
 * the owner remains above the frozen layer, while Groq/web stay available for current or missing
 * information. No native generative JNI runtime is reintroduced.
 */
class NikoLocalLlm(
    context: Context,
    @Suppress("UNUSED_PARAMETER") models: NikoModelManager,
) {
    private val appContext = context.applicationContext
    private val knowledge = NikoKnowledgeStore(appContext)
    private val structuredCloud = LeoStructuredGroq(appContext)
    private val microGpt = LeoMicroGptAsset(appContext)
    private val frozenManager = LeoFrozenBrainManager(appContext)
    private val frozenKnowledge = LeoFrozenKnowledgeStore(appContext)
    private val brainScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    @Volatile private var closed = false

    @Volatile var lastError: String? = null
        private set

    init {
        // The APK stays small. Installation is resumable and happens outside the response path,
        // so a first-run 500 MB download never blocks wake word, STT or the first spoken reply.
        brainScope.launch {
            delay(FROZEN_BRAIN_START_DELAY_MS)
            if (!closed) frozenManager.ensureInstalled()
        }
    }

    /** Pure Kotlin conversational generation is supported without loading JNI. */
    val runtimeSupported: Boolean get() = microGpt.isAvailable

    /** MicroGPT works immediately; the larger frozen knowledge layer can arrive later. */
    val isAvailable: Boolean get() = !closed && microGpt.isAvailable

    val preferredModel: NikoModelSpec get() = NikoModelCatalog.localLlmFast

    suspend fun prewarm(): Boolean = withContext(Dispatchers.IO) {
        if (closed) return@withContext false
        val ready = microGpt.prewarm()
        if (frozenManager.isInstalled()) runCatching { frozenKnowledge.prewarm() }
        lastError = if (ready) null else localModelError()
        ready
    }

    suspend fun reply(
        message: String,
        memoryContext: String = "",
        evidence: String = "",
    ): String? = withContext(Dispatchers.IO) {
        @Suppress("UNUSED_VARIABLE") val ignoredContext = memoryContext
        @Suppress("UNUSED_VARIABLE") val ignoredEvidence = evidence
        lastError = null
        if (closed) return@withContext null

        if (!NikoVisualContext.wantsScreenContext(message)) {
            // Personal/verified learned knowledge always wins over generic frozen knowledge.
            runCatching { knowledge.recall(message) }.getOrNull()?.let { learned ->
                return@withContext learned.answer
            }
            // Conversational families should never be answered by a random encyclopedia hit.
            microGpt.reply(message)?.let { generated ->
                return@withContext generated
            }
            // Static facts can now be answered entirely offline from the 500 MB brain.
            runCatching { frozenKnowledge.recall(message) }.getOrNull()?.let { frozen ->
                return@withContext frozen.answer
            }
        }

        lastError = localModelError()
        null
    }

    /**
     * Groq only compiles intention -> DSL; LeoStructuredPlanner still validates every resulting
     * action. MicroGPT and the frozen knowledge database never emit executable DSL or receive
     * permission to perform phone actions.
     */
    suspend fun completeStructured(instruction: String): String? {
        if (closed) return null
        val result = structuredCloud.complete(instruction)
        lastError = if (result == null) structuredCloud.lastError ?: localModelError() else null
        return result
    }

    fun release() {
        closed = true
        brainScope.cancel()
        frozenKnowledge.close()
    }

    private fun localModelError(): String = when {
        frozenManager.isInstalled() ->
            "Mi MicroGPT y mi cerebro congelado local están disponibles. Para datos actuales uso Groq o búsqueda web cuando hacen falta."
        else ->
            "Mi MicroGPT local ya funciona y mi cerebro congelado de 500 MB se instala en segundo plano. Para conocimiento que aún no tenga uso Groq o búsqueda web."
    }

    private companion object {
        const val FROZEN_BRAIN_START_DELAY_MS = 2_500L
    }
}
